- name: Disable and stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['distribution_major_version']|int > 6

- name: Disable and stop iptables(for 6 and 7 releases)
  service:
    name: iptables
    state: stopped
    enabled: no
  when: ansible_facts['distribution_major_version']|int < 7
