- name: Set prompt color for test
  copy:
    dest: /etc/profile.d/prompt_color.sh
    content: |
      if [ $UID -eq 0 ]; then
        export PS1='\[\033[0;32m\]\[\033[0;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[0;32m\]\[\033[00m\]\$ '
      fi

  when: (env is not defined or env == "test")

- name: Set prompt color for stage
  copy:
    dest: /etc/profile.d/prompt_color.sh
    content: |
      if [ $UID -eq 0 ]; then
        export PS1='\[\033[0;33m\]\[\033[0;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[0;33m\]\[\033[00m\]\$ '
      fi

  when: env is defined and env == "stage"
  
- name: Set prompt color for prod
  copy:
    dest: /etc/profile.d/prompt_color.sh
    content: |
      if [ $UID -eq 0 ]; then
        export PS1='\[\033[01;31m\]\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;31m\]\[\033[00m\]\$ '
      fi

  when: env is defined and env == "prod"
